server:
  port: 8100

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.sscs.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/sscs/"
  application:
    name: SSCS HMC Stub

  main:
    allow-bean-definition-overriding: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS:}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true

azure:
  application-insights:
    instrumentation-key: ${sscs.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
  service-bus:
    amqp-connection-string-template : ${AMQP_CONNECTION_STRING:amqps://%1s?amqp.idleTimeout=%2d}
    connection-postfix: ${HMC_STUB_TOPIC_CONNECTION_POSTFIX:.servicebus.windows.net}
    hmc-to-hearings-api:
      namespace: ${HMC_STUB_TOPIC_NAMESPACE:sscs-servicebus-aat}
      topicName: ${HMC_STUB_TOPIC_NAME:mock-hmc-to-cft-aat}
      subscriptionName: ${HMC_STUB_TOPIC_SUBSCRIPTION_NAME:mock-hmc-to-sscs-subscription-aat}
      receiveTimeout: ${HMC_STUB_TOPIC_RECEIVE_TIMEOUT:1}
      idleTimeout: ${HMC_STUB_TOPIC_IDLE_TIMEOUT:3600000}
      username: ${HMC_STUB_TOPIC_POLICY_NAME:SendAndListenSharedAccessKey}
      password: ${HMC_STUB_TOPIC_ACCESS_KEY:}
idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  s2s-auth:
    url: ${IDAM_S2S_URL:http://localhost:4502}
    name: ${S2S_NAME_SSCS_HEARINGS_API:sscs-hmc-stub}
    totp_secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: sscs
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:system.update@hmcts.net}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:Pa55word11}

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  caseTypeId: ${CORE_CASE_DATA_CASE_TYPE_ID:Benefit}
  jurisdictionId: ${CORE_CASE_DATA_JURISDICTION_ID:SSCS}
