apiVersion: v2
appVersion: "1.0"
description: A Helm chart for sscs-hmc-stub App
name: sscs-hmc-stub
home: https://github.com/hmcts/sscs-hmc-stub
version: 0.0.3
maintainers:
  - name: HMCTS SSCS team
dependencies:
  - name: java
    version: 4.0.11
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
